#!/usr/bin/env bash
# phase 30 — enable services, install the SDDM config + Wayland session entry.

_enable_system() {  # <unit> — enable (+start) if present
    command -v systemctl >/dev/null 2>&1 || return 0
    if systemctl list-unit-files "$1" 2>/dev/null | grep -q "^$1"; then
        sudo_run systemctl enable "$1" && ok "enabled $1" || warn "could not enable $1"
    else
        info "service not present, skipping: $1"
    fi
}

phase_services() {
    step "30 · services + greeter + session entry"
    command -v systemctl >/dev/null 2>&1 || { warn "no systemd — skipping service enablement (enable equivalents in your init)."; return 0; }

    # ── user audio stack (socket-activated) ──
    run systemctl --user enable pipewire.socket pipewire-pulse.socket wireplumber.service 2>/dev/null \
        || info "pipewire user units will come up with the session"

    # ── system services ──
    _enable_system NetworkManager.service
    _enable_system bluetooth.service
    _enable_system power-profiles-daemon.service

    # ── Wayland session entry — installed to BOTH standard dirs so ReGreet finds
    #    it regardless of its scan paths. ──
    local tmpl="$DOTREPO/templates/hyprland-de.desktop.in"
    local wrap="$HOME/.config/hypr/start-hyprland.sh"
    if [ -r "$tmpl" ]; then
        local d
        for d in /usr/share/wayland-sessions /usr/local/share/wayland-sessions; do
            sudo_run install -d "$d"
            if [ "${DRY_RUN:-0}" = "1" ]; then info "would write $d/hyprland-de.desktop (Exec=$wrap)"
            else sed "s|@EXEC@|$wrap|g" "$tmpl" | sudo_run tee "$d/hyprland-de.desktop" >/dev/null && ok "installed session entry $d/hyprland-de.desktop"; fi
        done
    fi

    # ── greetd greeter (Quickshell/QML, themed) via cage; zero Xorg ──
    if command -v greetd >/dev/null 2>&1 || pkg_present greetd; then
        sudo_run install -d /etc/greetd
        sudo_run install -m 644 "$DOTREPO/system/greetd/config.toml"  /etc/greetd/config.toml  && ok "installed greetd config"

        # The themed greeter is a Quickshell config installed to the system XDG
        # dir so the `greeter` user can read it (qs -c hyprshell-greeter).
        sudo_run install -d /etc/xdg/quickshell/hyprshell-greeter
        sudo_run install -m 644 "$DOTREPO/system/greeter/shell.qml" /etc/xdg/quickshell/hyprshell-greeter/shell.qml \
            && ok "installed Quickshell greeter (/etc/xdg/quickshell/hyprshell-greeter)"
        # brand mark shown at the top of the greeter (referenced as logo.png there)
        [ -r "$DOTREPO/system/branding/hypr-shell-icon.png" ] && \
            sudo_run install -m 644 "$DOTREPO/system/branding/hypr-shell-icon.png" /etc/xdg/quickshell/hyprshell-greeter/logo.png

        # Greeter wrapper — config.toml's command points here. A real script (not
        # an `env …` prefix, which greetd word-splits and mis-parses, nor a service
        # drop-in, whose env greetd may not pass through) is the place to set env:
        #   WLR_NO_HARDWARE_CURSORS — fixes the inverted virtio-gpu / flaky `xe` cursor.
        #   WLR_RENDERER_ALLOW_SOFTWARE (VM) — cage software-GL fallback.
        #   XDG_CONFIG_DIRS/XDG_CACHE_HOME — so `qs -c` finds the config + has a
        #     writable cache as the greeter user.
        # Runs the QML greeter, falling back to ReGreet if qs exits nonzero (a QML
        # error must never lock you out of login).
        if [ "${DRY_RUN:-0}" = "1" ]; then info "would write /usr/local/bin/hypr-shell-greeter (cage → qs greeter)"
        else
            { printf '#!/bin/sh\n# Generated by hypr-shell phase 30. Greeter session wrapper run by greetd.\n'
              printf 'export WLR_NO_HARDWARE_CURSORS=1\n'
              [ "${IS_VM:-0}" = "1" ] && printf 'export WLR_RENDERER_ALLOW_SOFTWARE=1\n'
              printf 'export XDG_CONFIG_DIRS="${XDG_CONFIG_DIRS:-/etc/xdg}"\n'
              printf 'export XDG_CACHE_HOME="${XDG_CACHE_HOME:-/tmp/hyprshell-greeter}"\n'
              # cage offers no server-side decorations, so Qt draws its OWN client-side
              # titlebar (min/max/close) around the greeter — which is why it looked
              # "in a window". Disable Qt CSD so the greeter is borderless/fullscreen.
              printf 'export QT_QPA_PLATFORM=wayland\n'
              printf 'export QT_WAYLAND_DISABLE_WINDOWDECORATION=1\n'
              printf 'exec cage -s -- sh -c "qs -c hyprshell-greeter || regreet"\n'
            } | sudo_run tee /usr/local/bin/hypr-shell-greeter >/dev/null \
              && sudo_run chmod 755 /usr/local/bin/hypr-shell-greeter \
              && ok "installed greeter wrapper (Quickshell greeter, regreet fallback)"
        fi
        # Remove the earlier drop-in attempt if a previous run left one.
        [ -f /etc/systemd/system/greetd.service.d/hypr-shell.conf ] && sudo_run rm -f /etc/systemd/system/greetd.service.d/hypr-shell.conf
        sudo_run install -m 644 "$DOTREPO/system/greetd/regreet.toml" /etc/greetd/regreet.toml && ok "installed ReGreet config (fallback)"
        # PAM keyring unlock: login keyring opens with your password at the greeter,
        # so the "login keyring did not get unlocked" prompt never appears.
        if [ -f /usr/lib/security/pam_gnome_keyring.so ] || [ -f /lib/security/pam_gnome_keyring.so ] || pkg_present gnome-keyring; then
            sudo_run install -m 644 "$DOTREPO/system/pam.d/greetd" /etc/pam.d/greetd && ok "installed greetd PAM (gnome-keyring auto-unlock)"
        else
            info "gnome-keyring not present — skipped greetd PAM keyring integration."
        fi
        # Only enable greetd if a greeter binary exists (qs is primary, regreet is
        # the fallback). Otherwise cage's "Failed to spawn client" loops a black
        # screen — refuse to enable and say how to finish.
        if command -v qs >/dev/null 2>&1 || command -v quickshell >/dev/null 2>&1 || command -v regreet >/dev/null 2>&1 || pkg_present quickshell; then
            _enable_system greetd.service
            info "greetd → cage → Quickshell greeter (regreet fallback), lists 'Hyprland (DE)'. Disable any other display-manager.service first."
        else
            warn "no greeter found (quickshell/regreet) — NOT enabling greetd.service to avoid a broken boot."
            warn "Install with:  sudo pacman -S quickshell greetd-regreet  &&  sudo systemctl enable greetd.service"
        fi
    else
        warn "greetd not installed — start the session from a TTY with start-hyprland.sh, or enable a greeter."
    fi

    ok "services done"
}
