import QtQuick
import QtQuick.Effects
import QtQuick.Dialogs
import Quickshell
import Quickshell.Wayland
import Quickshell.Hyprland
import Quickshell.Io
import Quickshell.Services.Pipewire

// Settings — a universal, themed settings window (Super+, · Control Center gear ·
// Spotlight "Settings"). Sidebar nav + content. Panes: System/Diagnostics,
// Displays, Networking, Default Apps, Keyboard, Shortcuts, Theme & Accent, User.
// Mirrors ControlCenter.qml's structure; all colours from Theme.qml.
//
// Hyprland is Lua-configured, so live changes go through `hyprctl eval 'hl…'`
// (plain `hyprctl keyword` is rejected). Persistent changes are written to
// ~/.config/hypr/generated/user.lua (sourced last by hyprland.lua).
Scope {
    id: root

    function g(c) { return String.fromCodePoint(c) }
    readonly property string home: Quickshell.env("HOME")

    property int pane: 0
    readonly property var navItems: [
        { ic: 0xF02FB, label: "System" },
        { ic: 0xF0379, label: "Displays" },
        { ic: 0xF05A9, label: "Networking" },
        { ic: 0xF0614, label: "Default Apps" },
        { ic: 0xF030C, label: "Keyboard" },
        { ic: 0xF11C7, label: "Shortcuts" },
        { ic: 0xF0241, label: "Theme" },
        { ic: 0xF0DC3, label: "Dock" },
        { ic: 0xF0004, label: "User" }
    ]
    onPaneChanged: {
        if (pane === 2) { wifiDevProbe.running = true; wifiState.running = true; wifiScan.running = true; vpnScan.running = true; netProc.running = true; sshProc.running = true }
        else if (pane === 4) kbProc.running = true
        else if (pane === 5) scProc.running = true
        else if (pane === 7) faceProc.running = true
    }

    // ── persisted override state ───────────────────────────────────────────────
    property int  gapsIn: 6
    property int  gapsOut: 14
    property int  borderSize: 1
    property bool displaysDirty: false
    property var  monList: []
    property string kbLayout: "us,ge"
    property bool kbDirty: false

    function hex6(c) { var s = String(c).replace("#", ""); return s.length === 8 ? s.slice(2) : s }
    function curMode(m) { return m.width + "x" + m.height + "@" + m.refreshRate }

    function writeOverrides() {
        var s = "-- AUTO-GENERATED by the Quickshell Settings app. Do not edit by hand.\n"
        var gen = "hl.config({ general = { gaps_in = " + root.gapsIn
                + ", gaps_out = " + root.gapsOut + ", border_size = " + root.borderSize
        if (Globals.tintBorders)
            gen += ", col = { active_border = \"rgba(" + root.hex6(Globals.accentColor) + "ff)\" }"
        gen += " } })\n"
        s += gen
        s += root.animBlockPersist()
        if (root.kbDirty) s += "hl.config({ input = { kb_layout = \"" + root.kbLayout + "\" } })\n"
        if (root.displaysDirty)
            for (var i = 0; i < root.monList.length; i++) s += root.monLua(root.monList[i]) + "\n"
        luaWriter.command = ["sh", "-c", "mkdir -p \"" + root.home + "/.config/hypr/generated\"; cat > \""
            + root.home + "/.config/hypr/generated/user.lua\" <<'QS_EOF'\n" + s + "QS_EOF\n"]
        luaWriter.running = false; luaWriter.running = true
    }
    function monLua(o) {
        return 'hl.monitor({ output = "' + o.output + '", mode = "' + o.mode
             + '", position = "' + o.position + '", scale = ' + o.scale + ' })'
    }
    Process { id: luaWriter }
    Process { id: jsonWriter }

    // ── Animations (speed multiplier → Hyprland animation overrides) ────────────
    // Scaling the per-leaf `speed` (duration in ds): higher multiplier → smaller
    // speed → faster. m=0 disables animations entirely.
    readonly property var animBase: [
        { leaf: "global",     s: 9,    bz: "easeOutQuint" },
        { leaf: "border",     s: 5.39, bz: "easeOutQuint" },
        { leaf: "windows",    s: 5,    spring: "easy", style: "popin 88%" },
        { leaf: "windowsOut", s: 3,    bz: "linear",   style: "popin 88%" },
        { leaf: "fade",       s: 3.5,  bz: "quick" },
        { leaf: "layers",     s: 4,    bz: "easeOutQuint", style: "fade" },
        { leaf: "workspaces", s: 5,    bz: "easeOutQuint", style: "slide" }
    ]
    function animLuaLines(m) {
        var L = []
        if (m <= 0) { L.push("hl.config({ animations = { enabled = false } })"); return L }
        L.push("hl.config({ animations = { enabled = true } })")
        for (var i = 0; i < root.animBase.length; i++) {
            var a = root.animBase[i], sp = (a.s / m).toFixed(2)
            var s = 'hl.animation({ leaf = "' + a.leaf + '", enabled = true, speed = ' + sp
            if (a.spring) s += ', spring = "' + a.spring + '"'
            if (a.bz) s += ', bezier = "' + a.bz + '"'
            if (a.style) s += ', style = "' + a.style + '"'
            L.push(s + ' })')
        }
        return L
    }
    // persisted form: empty at default speed (let hyprland.lua's defaults stand)
    function animBlockPersist() {
        var m = Globals.animationSpeed
        return Math.abs(m - 1) < 0.001 ? "" : (root.animLuaLines(m).join("\n") + "\n")
    }
    // live-apply: one `hyprctl eval` per statement (the known-good single-call form)
    function applyAnimations() {
        var sh = root.animLuaLines(Globals.animationSpeed).map(function (c) { return "hyprctl eval '" + c + "'" }).join("; ")
        Quickshell.execDetached(["sh", "-c", sh])
        root.writeOverrides()
    }
    function setAnim(m) { Globals.animationSpeed = m; root.writePrefs(); root.applyAnimations() }

    // ── Layout (gaps/border) ────────────────────────────────────────────────────
    function applyGaps() {
        Quickshell.execDetached(["hyprctl", "eval",
            "hl.config({ general = { gaps_in = " + root.gapsIn + ", gaps_out = " + root.gapsOut
            + ", border_size = " + root.borderSize + " } })"])
        root.writeOverrides()
    }

    // ── shell prefs (accent + dock) persisted to user-theme.json ──────────────────
    function writePrefs() {
        var s = '{ "accent": "' + String(Globals.accentColor) + '", "tintBorders": ' + (Globals.tintBorders ? "true" : "false")
              + ', "dockEnabled": ' + (Globals.dockEnabled ? "true" : "false")
              + ', "dockAutohide": ' + (Globals.dockAutohide ? "true" : "false")
              + ', "animationSpeed": ' + Number(Globals.animationSpeed)
              + ', "colorScheme": "' + Globals.colorScheme + '" }'
        jsonWriter.command = ["sh", "-c", "cat > \"" + root.home + "/.config/quickshell/user-theme.json\" <<'QS_EOF'\n" + s + "\nQS_EOF\n"]
        jsonWriter.running = false; jsonWriter.running = true
    }
    function setAccent(hex) {
        Globals.accentColor = hex
        root.writePrefs()
        if (Globals.tintBorders) root.applyBorder()
    }
    // light/dark for external GTK + Qt apps (the shell itself is always dark)
    function setColorScheme(mode) {
        Globals.colorScheme = mode
        root.writePrefs()
        Quickshell.execDetached(["sh", "-c", "\"" + root.home + "/.config/quickshell/scripts/colorscheme.sh\" " + mode])
    }
    function applyBorder() {
        if (Globals.tintBorders)
            Quickshell.execDetached(["hyprctl", "eval",
                "hl.config({ general = { col = { active_border = \"rgba(" + root.hex6(Globals.accentColor) + "ff)\" } } })"])
        root.writeOverrides()
    }

    // ── Displays ──────────────────────────────────────────────────────────────
    property var monitors: []
    function isLaptop(m) { return ((m && m.name) ? m.name : "").toLowerCase().indexOf("edp") >= 0 }
    // change scale/mode of one monitor, keep everyone's current position
    function applyChange(opts) {
        var ms = root.monitors; if (!ms || ms.length === 0) return
        var out = ms.map(function (m) {
            var sc = (opts.name === m.name && opts.scale !== undefined) ? opts.scale : m.scale
            var mode = (opts.name === m.name && opts.mode !== undefined) ? opts.mode : root.curMode(m)
            return { output: m.name, mode: mode, position: (m.x + "x" + m.y), scale: sc }
        })
        root.monList = out; root.displaysDirty = true
        for (var k = 0; k < out.length; k++) Quickshell.execDetached(["hyprctl", "eval", root.monLua(out[k])])
        root.writeOverrides(); monRefresh.restart()
    }
    // drag-arrange: snap the dragged monitor to a side of the other (≤2 monitors)
    function snapArrange(name, lx, ly) {
        var ms = root.monitors; if (!ms || ms.length < 2) { monRefresh.restart(); return }
        var dragged = null, anchor = null
        for (var i = 0; i < ms.length; i++) { if (ms[i].name === name) dragged = ms[i]; else if (!anchor) anchor = ms[i] }
        if (!dragged || !anchor) return
        var dlw = dragged.width / dragged.scale, dlh = dragged.height / dragged.scale
        var alw = anchor.width / anchor.scale, alh = anchor.height / anchor.scale
        var dx = (lx + dlw / 2) - (alw / 2), dy = (ly + dlh / 2) - (alh / 2)
        var dxp, dyp
        if (Math.abs(dx) >= Math.abs(dy)) { dxp = dx >= 0 ? alw : -dlw; dyp = 0 }
        else { dxp = 0; dyp = dy >= 0 ? alh : -dlh }
        var minx = Math.min(0, dxp), miny = Math.min(0, dyp)
        var aPos = (-minx) + "x" + (-miny), dPos = (dxp - minx) + "x" + (dyp - miny)
        root.monList = [
            { output: anchor.name, mode: root.curMode(anchor), position: aPos, scale: anchor.scale },
            { output: dragged.name, mode: root.curMode(dragged), position: dPos, scale: dragged.scale }
        ]
        root.displaysDirty = true
        for (var k = 0; k < root.monList.length; k++) Quickshell.execDetached(["hyprctl", "eval", root.monLua(root.monList[k])])
        root.writeOverrides(); monRefresh.restart()
    }

    // ── Default apps ──────────────────────────────────────────────────────────
    property var defaults: ({})        // current default desktop-id per category
    property var appChoices: ({})      // category → [desktop-ids] that handle it (gio)
    readonly property var appCats: [
        { key: "Browser",      ic: 0xF059F, mime: "x-scheme-handler/https", mimes: ["x-scheme-handler/https", "x-scheme-handler/http", "text/html"] },
        { key: "Mail",         ic: 0xF01EE, mime: "x-scheme-handler/mailto", mimes: ["x-scheme-handler/mailto"] },
        { key: "Text Editor",  ic: 0xF021A, mime: "text/plain", mimes: ["text/plain"] },
        { key: "Image Viewer", ic: 0xF021F, mime: "image/png", mimes: ["image/png", "image/jpeg", "image/gif", "image/webp"] },
        { key: "Video Player", ic: 0xF0567, mime: "video/mp4", mimes: ["video/mp4", "video/x-matroska", "video/webm"] },
        { key: "File Manager", ic: 0xF0256, mime: "inode/directory", mimes: ["inode/directory"] }
    ]
    function entryForId(id) {
        var want = String(id || "").replace(/\.desktop$/, "")
        var apps = DesktopEntries.applications ? DesktopEntries.applications.values : []
        for (var i = 0; i < apps.length; i++) if (apps[i] && apps[i].id === want) return apps[i]
        return null
    }
    function appNameForId(id) { var e = root.entryForId(id); return e ? (e.name || e.id) : (id ? id.replace(/\.desktop$/, "") : "—") }
    function setDefaultApp(cat, deskId) {
        var c = null
        for (var i = 0; i < root.appCats.length; i++) if (root.appCats[i].key === cat) c = root.appCats[i]
        if (!c) return
        var cmd = ""
        for (var m = 0; m < c.mimes.length; m++) cmd += "xdg-mime default '" + deskId + "' '" + c.mimes[m] + "'; "
        if (cat === "Browser") cmd += "xdg-settings set default-web-browser '" + deskId + "'; "
        Quickshell.execDetached(["sh", "-c", cmd])
        defRefresh.restart()
    }

    // ── Networking ──────────────────────────────────────────────────────────────
    property var wifiList: []
    property bool wifiOn: true
    property bool hasWifi: true     // false when no wifi device exists (e.g. a VM)
    readonly property var wiredList: (root.netActive || []).filter(function (c) { return (c.type || "").indexOf("ethernet") >= 0 })
    property string pwTarget: ""
    property string pwText: ""
    property var vpnList: []
    property var netActive: []     // [{name,type,dev,state}]
    property var ipList: []        // ["wlo1: 192.168.x/24"]
    property var sshHosts: []
    function connectWifi(ssid, sec) {
        if (sec && sec !== "" && root.pwText === "") { root.pwTarget = (root.pwTarget === ssid) ? "" : ssid; return }
        var cmd = ["nmcli", "device", "wifi", "connect", ssid]
        if (root.pwText !== "") cmd = cmd.concat(["password", root.pwText])
        Quickshell.execDetached(cmd); root.pwTarget = ""; root.pwText = ""; wifiRescan.restart()
    }

    // ── refresh probes ────────────────────────────────────────────────────────
    function refresh() { diagProc.running = true; layoutProc.running = true; monProc.running = true; defProc.running = true; choicesProc.running = true }
    Connections { target: Globals; function onSettingsOpenChanged() { if (Globals.settingsOpen) root.refresh() } }
    IpcHandler {
        target: "settings"
        function toggle(): void { Globals.settingsOpen = !Globals.settingsOpen }
        function show(): void { Globals.settingsOpen = true }
        function hide(): void { Globals.settingsOpen = false }
    }

    // diagnostics (generic, app-agnostic)
    property var diag: ({})
    Process {
        id: diagProc
        command: ["sh", "-c",
            'echo "gsession=$(systemctl --user is-active graphical-session.target 2>/dev/null)";' +
            'echo "portal=$(systemctl --user is-active xdg-desktop-portal 2>/dev/null)";' +
            'echo "portal_hypr=$(systemctl --user is-active xdg-desktop-portal-hyprland 2>/dev/null)";' +
            'echo "portal_gtk=$(systemctl --user is-active xdg-desktop-portal-gtk 2>/dev/null)";' +
            'echo "handoff=$(busctl --user introspect org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.OpenURI >/dev/null 2>&1 && echo ok || echo fail)";' +
            'echo "browser=$(xdg-settings get default-web-browser 2>/dev/null)";' +
            'echo "gpu=$(lspci -k 2>/dev/null | grep -A3 -iE \"VGA|Display|3D\" | grep -i \"driver in use\" | head -1 | sed \"s/.*use: //\")";' +
            'echo "mem=$(free -m 2>/dev/null | awk \"/Mem:/{print \\$3\\\"/\\\"\\$2\\\" MB\\\"}\")";' +
            'echo "disk=$(df -h / 2>/dev/null | awk \"NR==2{print \\$3\\\"/\\\"\\$2\\\" (\\\"\\$5\\\")\\\"}\")"' ]
        stdout: StdioCollector { onStreamFinished: { var d = {}, ls = this.text.split("\n"); for (var i = 0; i < ls.length; i++) { var k = ls[i].indexOf("="); if (k > 0) d[ls[i].slice(0, k)] = ls[i].slice(k + 1) } root.diag = d } }
    }
    Process {
        id: layoutProc
        command: ["sh", "-c",
            'gi=$(hyprctl getoption general:gaps_in -j); go=$(hyprctl getoption general:gaps_out -j); bs=$(hyprctl getoption general:border_size -j);' +
            'echo "in=$(echo \"$gi\" | grep -oE \"[0-9]+\" | head -1)";' +
            'echo "out=$(echo \"$go\" | grep -oE \"[0-9]+\" | head -1)";' +
            'echo "border=$(echo \"$bs\" | grep -oE \"\\\"int\\\": *[0-9]+\" | grep -oE \"[0-9]+\")"' ]
        stdout: StdioCollector { onStreamFinished: { var ls = this.text.split("\n"); for (var i = 0; i < ls.length; i++) { var p = ls[i].split("="); if (p[0] === "in" && p[1] !== "") root.gapsIn = parseInt(p[1]); else if (p[0] === "out" && p[1] !== "") root.gapsOut = parseInt(p[1]); else if (p[0] === "border" && p[1] !== "") root.borderSize = parseInt(p[1]) } } }
    }
    Process { id: monProc; command: ["hyprctl", "monitors", "-j"]; stdout: StdioCollector { onStreamFinished: { try { root.monitors = JSON.parse(this.text) } catch (e) { root.monitors = [] } } } }
    Timer { id: monRefresh; interval: 350; onTriggered: monProc.running = true }
    Process {
        id: defProc
        command: ["sh", "-c",
            'echo "Browser=$(xdg-mime query default x-scheme-handler/https 2>/dev/null)";' +
            'echo "Mail=$(xdg-mime query default x-scheme-handler/mailto 2>/dev/null)";' +
            'echo "Text Editor=$(xdg-mime query default text/plain 2>/dev/null)";' +
            'echo "Image Viewer=$(xdg-mime query default image/png 2>/dev/null)";' +
            'echo "Video Player=$(xdg-mime query default video/mp4 2>/dev/null)";' +
            'echo "File Manager=$(xdg-mime query default inode/directory 2>/dev/null)"' ]
        stdout: StdioCollector { onStreamFinished: { var d = {}, ls = this.text.split("\n"); for (var i = 0; i < ls.length; i++) { var k = ls[i].indexOf("="); if (k > 0) d[ls[i].slice(0, k)] = ls[i].slice(k + 1) } root.defaults = d } }
    }
    Timer { id: defRefresh; interval: 400; onTriggered: { defProc.running = true; choicesProc.running = true } }
    // which apps handle each category (gio mime recommended/registered)
    Process {
        id: choicesProc
        command: ["sh", "-c",
            'for pair in "Browser:x-scheme-handler/https" "Mail:x-scheme-handler/mailto" "Text Editor:text/plain" "Image Viewer:image/png" "Video Player:video/mp4" "File Manager:inode/directory"; do ' +
            '  cat="${pair%%:*}"; mime="${pair#*:}"; ' +
            '  ids=$(gio mime "$mime" 2>/dev/null | awk "/Recommended applications:/{f=1;next} /^[^\\t]/{f=0} f{gsub(/^\\t/,\\\"\\\");print}"); ' +
            '  [ -z "$ids" ] && ids=$(gio mime "$mime" 2>/dev/null | awk "/Registered applications:/{f=1;next} /Recommended applications:/{f=0} /^[^\\t]/{f=0} f{gsub(/^\\t/,\\\"\\\");print}"); ' +
            '  for id in $ids; do printf "%s\\t%s\\n" "$cat" "$id"; done; ' +
            'done' ]
        stdout: StdioCollector { onStreamFinished: { var d = {}, ls = this.text.split("\n"); for (var i = 0; i < ls.length; i++) { var t = ls[i].split("\t"); if (t.length === 2 && t[1]) { if (!d[t[0]]) d[t[0]] = []; d[t[0]].push(t[1]) } } root.appChoices = d } }
    }
    // networking probes
    Process { id: wifiDevProbe; command: ["sh", "-c", "nmcli -t -f TYPE device status 2>/dev/null | grep -qx wifi && echo yes || echo no"]; stdout: StdioCollector { onStreamFinished: root.hasWifi = this.text.trim() === "yes" } }
    Process { id: wifiState; command: ["nmcli", "-t", "-f", "WIFI", "radio"]; stdout: StdioCollector { onStreamFinished: root.wifiOn = this.text.trim() === "enabled" } }
    Process {
        id: wifiScan; command: ["nmcli", "-t", "-f", "IN-USE,SIGNAL,SECURITY,SSID", "device", "wifi", "list"]
        stdout: StdioCollector { onStreamFinished: { var ls = this.text.split("\n"), seen = {}, arr = []; for (var i = 0; i < ls.length; i++) { if (!ls[i]) continue; var p = ls[i].split(":"); var ssid = p.slice(3).join(":"); if (!ssid || seen[ssid]) continue; seen[ssid] = 1; arr.push({ ssid: ssid, signal: parseInt(p[1]) || 0, sec: p[2] || "", active: p[0] === "*" }) } arr.sort(function (a, b) { return (b.active - a.active) || (b.signal - a.signal) }); root.wifiList = arr } }
    }
    Timer { id: wifiRescan; interval: 2500; onTriggered: { wifiState.running = true; wifiScan.running = true } }
    Process {
        id: vpnScan; command: ["sh", "-c", "nmcli -t -f NAME,TYPE,ACTIVE connection show 2>/dev/null"]
        stdout: StdioCollector { onStreamFinished: { var ls = this.text.split("\n"), arr = []; for (var i = 0; i < ls.length; i++) { if (!ls[i]) continue; var p = ls[i].split(":"); var type = p[p.length - 2], active = p[p.length - 1] === "yes"; var name = p.slice(0, p.length - 2).join(":"); if (type && (type.indexOf("vpn") >= 0 || type.indexOf("wireguard") >= 0)) arr.push({ name: name, active: active }) } root.vpnList = arr } }
    }
    Timer { id: vpnRescan; interval: 1500; onTriggered: vpnScan.running = true }
    Process {
        id: netProc
        command: ["sh", "-c", 'nmcli -t -f NAME,TYPE,DEVICE,STATE connection show --active 2>/dev/null; echo "==="; ip -4 -o addr show scope global 2>/dev/null | awk "{print \\$2\\\": \\\"\\$4}"' ]
        stdout: StdioCollector { onStreamFinished: { var parts = this.text.split("==="); var a = [], ip = []; var l1 = parts[0].split("\n"); for (var i = 0; i < l1.length; i++) { if (!l1[i]) continue; var p = l1[i].split(":"); a.push({ name: p[0], type: p[1], dev: p[2], state: p[3] }) } if (parts[1]) { var l2 = parts[1].split("\n"); for (var j = 0; j < l2.length; j++) if (l2[j].trim()) ip.push(l2[j].trim()) } root.netActive = a; root.ipList = ip } }
    }
    Process {
        id: sshProc; command: ["sh", "-c", "grep -iE '^[[:space:]]*Host[[:space:]]' \"$HOME/.ssh/config\" 2>/dev/null | awk '{for(i=2;i<=NF;i++)print $i}' | grep -v '[*?]' | sort -u"]
        stdout: StdioCollector { onStreamFinished: { var ls = this.text.split("\n"), arr = []; for (var i = 0; i < ls.length; i++) if (ls[i].trim()) arr.push(ls[i].trim()); root.sshHosts = arr } }
    }
    // keyboard layout
    Process { id: kbProc; command: ["hyprctl", "getoption", "input:kb_layout", "-j"]; stdout: StdioCollector { onStreamFinished: { try { var j = JSON.parse(this.text); if (j && j.str) root.kbLayout = j.str } catch (e) {} } } }
    function applyKb(csv) { root.kbLayout = csv; root.kbDirty = true; Quickshell.execDetached(["hyprctl", "eval", "hl.config({ input = { kb_layout = \"" + csv + "\" } })"]); root.writeOverrides() }
    readonly property var kbPresets: [
        { c: "us", n: "English (US)" }, { c: "gb", n: "English (UK)" },
        { c: "ge", n: "Georgian" }, { c: "ru", n: "Russian" }, { c: "ua", n: "Ukrainian" },
        { c: "de", n: "German" }, { c: "at", n: "German (Austria)" }, { c: "ch", n: "Swiss" },
        { c: "fr", n: "French" }, { c: "be", n: "Belgian" }, { c: "ca", n: "French (Canada)" },
        { c: "es", n: "Spanish" }, { c: "latam", n: "Spanish (Latin America)" },
        { c: "it", n: "Italian" }, { c: "pt", n: "Portuguese" }, { c: "br", n: "Portuguese (Brazil)" },
        { c: "nl", n: "Dutch" }, { c: "tr", n: "Turkish" }, { c: "gr", n: "Greek" },
        { c: "pl", n: "Polish" }, { c: "cz", n: "Czech" }, { c: "sk", n: "Slovak" },
        { c: "hu", n: "Hungarian" }, { c: "ro", n: "Romanian" }, { c: "bg", n: "Bulgarian" },
        { c: "se", n: "Swedish" }, { c: "no", n: "Norwegian" }, { c: "fi", n: "Finnish" },
        { c: "dk", n: "Danish" }, { c: "is", n: "Icelandic" },
        { c: "lt", n: "Lithuanian" }, { c: "lv", n: "Latvian" }, { c: "ee", n: "Estonian" },
        { c: "rs", n: "Serbian" }, { c: "hr", n: "Croatian" }, { c: "si", n: "Slovenian" },
        { c: "by", n: "Belarusian" }, { c: "kz", n: "Kazakh" }, { c: "am", n: "Armenian" },
        { c: "az", n: "Azerbaijani" }, { c: "il", n: "Hebrew" }, { c: "ara", n: "Arabic" },
        { c: "ir", n: "Persian" }, { c: "in", n: "Indian" }, { c: "jp", n: "Japanese" },
        { c: "kr", n: "Korean" }, { c: "cn", n: "Chinese" }, { c: "th", n: "Thai" },
        { c: "vn", n: "Vietnamese" }
    ]
    // shortcuts (rendered from SHORTCUTS.md)
    property string shortcutsMd: ""
    Process { id: scProc; command: ["sh", "-c", "cat \"$HOME/.config/hypr/SHORTCUTS.md\" 2>/dev/null"]; stdout: StdioCollector { onStreamFinished: root.shortcutsMd = this.text } }
    function shortcutsModel() {
        var out = [], ls = root.shortcutsMd.split("\n")
        for (var i = 0; i < ls.length; i++) {
            var t = ls[i].trim()
            if (t.indexOf("## ") === 0) out.push({ h: true, a: t.slice(3), b: "" })
            else if (t.indexOf("|") === 0 && t.indexOf("---") < 0) {
                var cells = t.split("|").map(function (x) { return x.trim() }).filter(function (x) { return x !== "" })
                if (cells.length >= 2 && cells[0].toLowerCase() !== "shortcut")
                    out.push({ h: false, a: cells[0].replace(/`/g, ""), b: cells[1].replace(/\*\*/g, "").replace(/`/g, "") })
            }
        }
        return out
    }

    // accent presets
    readonly property var accents: [
        { name: "Blue", hex: "#0a84ff" }, { name: "Indigo", hex: "#5e5ce6" }, { name: "Purple", hex: "#bf5af2" },
        { name: "Pink", hex: "#ff375f" }, { name: "Red", hex: "#ff453a" }, { name: "Orange", hex: "#ff9f0a" },
        { name: "Yellow", hex: "#ffd60a" }, { name: "Green", hex: "#30d158" }, { name: "Teal", hex: "#40c8e0" },
        { name: "Graphite", hex: "#8e8e93" }
    ]

    // avatar
    property int avatarTick: 0
    property bool hasFace: false
    Process { id: faceProc; command: ["sh", "-c", "[ -f \"$HOME/.face\" ] && echo yes || echo no"]; stdout: StdioCollector { onStreamFinished: root.hasFace = this.text.trim() === "yes" } }
    Timer { id: faceRecheck; interval: 400; onTriggered: faceProc.running = true }
    FileDialog {
        id: avatarDlg; title: "Choose avatar image"; nameFilters: ["Images (*.png *.jpg *.jpeg *.webp *.bmp)"]
        onAccepted: {
            var p = String(selectedFile).replace(/^file:\/\//, "")
            Quickshell.execDetached(["sh", "-c", "cp \"" + p + "\" \"$HOME/.face\" && busctl call org.freedesktop.Accounts /org/freedesktop/Accounts/User$(id -u) org.freedesktop.Accounts.User SetIconFile s \"$HOME/.face\" 2>/dev/null || true"])
            root.avatarTick++; faceRecheck.restart()
        }
    }

    // ══════════════════════════════════════════════════════════════════════════
    PanelWindow {
        id: win
        visible: Globals.settingsOpen || closeTimer.running
        screen: { var s = Quickshell.screens, fm = Hyprland.focusedMonitor; if (fm) for (var i = 0; i < s.length; i++) if (s[i].name === fm.name) return s[i]; return s.length > 0 ? s[0] : null }
        color: "transparent"
        exclusionMode: ExclusionMode.Ignore
        WlrLayershell.namespace: "quickshell:settings"
        WlrLayershell.layer: WlrLayer.Overlay
        WlrLayershell.keyboardFocus: WlrKeyboardFocus.OnDemand
        anchors { top: true; bottom: true; left: true; right: true }

        Timer { id: closeTimer; interval: 260 }
        Connections { target: Globals; function onSettingsOpenChanged() { if (!Globals.settingsOpen) closeTimer.restart() } }

        // translucent scrim (Hyprland blurs the desktop behind it via a layer rule)
        Rectangle { anchors.fill: parent; color: Qt.rgba(0, 0, 0, 0.28); opacity: Globals.settingsOpen ? 1 : 0; Behavior on opacity { NumberAnimation { duration: Theme.durBase } } }
        MouseArea { anchors.fill: parent; onClicked: Globals.settingsOpen = false }

        Rectangle {
            id: card
            anchors.centerIn: parent
            width: 860; height: 600
            radius: Theme.radius; color: Theme.panel
            border.color: Theme.stroke; border.width: 1
            clip: true
            opacity: Globals.settingsOpen ? 1 : 0
            scale: Globals.settingsOpen ? 1 : 0.96
            Behavior on opacity { NumberAnimation { duration: Theme.durBase; easing.type: Easing.OutCubic } }
            Behavior on scale { NumberAnimation { duration: Theme.durBase; easing.type: Easing.OutCubic } }
            layer.enabled: true
            layer.effect: MultiEffect { shadowEnabled: true; shadowColor: Theme.shadow; shadowOpacity: 0.5; shadowBlur: 1.0; shadowVerticalOffset: 10; blurMax: 48 }

            MouseArea { anchors.fill: parent }
            Item {
                id: keyGrab
                anchors.fill: parent; focus: true
                Keys.onEscapePressed: Globals.settingsOpen = false
                Connections { target: Globals; function onSettingsOpenChanged() { if (Globals.settingsOpen) keyGrab.forceActiveFocus() } }
            }

            // ════════ reusable bits ════════
            component Dot: Rectangle { property string state: "info"; width: 9; height: 9; radius: 5; color: state === "ok" ? Theme.success : state === "bad" ? Theme.danger : Theme.fgDim }
            component Card: Rectangle {
                default property alias content: inner.data
                width: parent ? parent.width : 0
                implicitHeight: inner.implicitHeight + 24
                radius: Theme.radiusInner; color: Theme.elevated
                Column { id: inner; anchors.left: parent.left; anchors.right: parent.right; anchors.top: parent.top; anchors.margins: 12; spacing: 8 }
            }
            component SectionTitle: Text { color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; font.weight: Font.DemiBold; bottomPadding: 2 }
            component KV: Item {
                property string k: ""; property string v: ""; property string dot: ""
                property bool action: false; property string actionLabel: ""
                signal act()
                width: parent ? parent.width : 0; height: 26
                Text { anchors.left: parent.left; anchors.verticalCenter: parent.verticalCenter; text: k; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall }
                Row {
                    anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; spacing: 8
                    Text { anchors.verticalCenter: parent.verticalCenter; visible: !action && v !== ""; text: v; color: Theme.fgSecondary; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; elide: Text.ElideRight; width: Math.min(implicitWidth, 340) }
                    Rectangle { visible: action; anchors.verticalCenter: parent.verticalCenter; width: alab.implicitWidth + 18; height: 22; radius: 7; color: aMa.containsMouse ? Theme.accent : Theme.hover; Behavior on color { ColorAnimation { duration: 120 } }
                        Text { id: alab; anchors.centerIn: parent; text: actionLabel; color: aMa.containsMouse ? Theme.accentText : Theme.fg; font.family: Theme.fontText; font.pixelSize: 11; font.weight: Font.DemiBold }
                        MouseArea { id: aMa; anchors.fill: parent; hoverEnabled: true; cursorShape: Qt.PointingHandCursor; onClicked: act() } }
                    Dot { anchors.verticalCenter: parent.verticalCenter; visible: dot !== ""; state: dot }
                }
            }
            component Slider: Item {
                property string label: ""; property int value: 0; property int from: 0; property int to: 30
                signal moved(int v)
                height: 40; width: parent ? parent.width : 0
                Text { anchors.left: parent.left; anchors.top: parent.top; text: label; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall }
                Text { anchors.right: parent.right; anchors.top: parent.top; text: value; color: Theme.accent; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; font.weight: Font.DemiBold }
                Rectangle { id: trk; anchors.left: parent.left; anchors.right: parent.right; anchors.bottom: parent.bottom; anchors.bottomMargin: 4; height: 8; radius: 4; color: Theme.hover
                    Rectangle { height: parent.height; radius: 4; color: Theme.accent; width: parent.width * (value - from) / Math.max(1, to - from) }
                    Rectangle { width: 14; height: 14; radius: 7; color: "white"; anchors.verticalCenter: parent.verticalCenter; x: Math.max(0, Math.min(trk.width - width, trk.width * (value - from) / Math.max(1, to - from) - width / 2)) }
                    MouseArea { anchors.fill: parent; anchors.topMargin: -8; anchors.bottomMargin: -8; function pick(mx) { var f = Math.max(0, Math.min(1, mx / trk.width)); return Math.round(from + f * (to - from)) } onPressed: function (m) { moved(pick(m.x)) } onPositionChanged: function (m) { if (pressed) moved(pick(m.x)) } }
                }
            }
            component Toggle: Rectangle {
                property bool on: false
                signal toggled()
                width: 40; height: 24; radius: 12; color: on ? Theme.accent : Theme.hover; Behavior on color { ColorAnimation { duration: 150 } }
                Rectangle { width: 18; height: 18; radius: 9; color: "white"; anchors.verticalCenter: parent.verticalCenter; x: parent.on ? parent.width - width - 3 : 3; Behavior on x { NumberAnimation { duration: 150 } } }
                MouseArea { anchors.fill: parent; cursorShape: Qt.PointingHandCursor; onClicked: toggled() }
            }
            component Pill: Rectangle {
                property string label: ""; property bool primary: false
                signal go()
                width: pl.implicitWidth + 22; height: 28; radius: 8
                color: plMa.containsMouse ? Theme.accent : (primary ? Theme.accent : Theme.elevated)
                Behavior on color { ColorAnimation { duration: 120 } }
                Text { id: pl; anchors.centerIn: parent; text: label; color: (plMa.containsMouse || primary) ? Theme.accentText : Theme.fg; font.family: Theme.fontText; font.pixelSize: 11; font.weight: Font.DemiBold }
                MouseArea { id: plMa; anchors.fill: parent; hoverEnabled: true; cursorShape: Qt.PointingHandCursor; onClicked: go() }
            }

            // ════════ layout: sidebar + content ════════
            Row {
                anchors.fill: parent; spacing: 0
                Rectangle {
                    width: 210; height: parent.height; color: Theme.bg
                    Column {
                        anchors.left: parent.left; anchors.right: parent.right; anchors.top: parent.top; anchors.margins: 14; spacing: 12
                        Text { text: "Settings"; color: Theme.fg; font.family: Theme.fontDisplay; font.pixelSize: Theme.fsLarge; font.weight: Font.Bold; bottomPadding: 2 }
                        Column {
                            width: parent.width; spacing: 2
                            Repeater {
                                model: root.navItems
                                delegate: Rectangle {
                                    required property var modelData
                                    required property int index
                                    width: parent.width; height: 36; radius: Theme.radiusInner
                                    readonly property bool sel: root.pane === index
                                    color: sel ? Theme.accent : (nMa.containsMouse ? Theme.hover : "transparent")
                                    Behavior on color { ColorAnimation { duration: 120 } }
                                    Row {
                                        anchors.left: parent.left; anchors.leftMargin: 11; anchors.verticalCenter: parent.verticalCenter; spacing: 11
                                        Text { anchors.verticalCenter: parent.verticalCenter; width: 18; text: root.g(modelData.ic); font.family: Theme.fontMono; font.pixelSize: 15; color: parent.parent.sel ? Theme.accentText : Theme.fg }
                                        Text { anchors.verticalCenter: parent.verticalCenter; text: modelData.label; color: parent.parent.sel ? Theme.accentText : Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; font.weight: parent.parent.sel ? Font.DemiBold : Font.Medium }
                                    }
                                    MouseArea { id: nMa; anchors.fill: parent; hoverEnabled: true; cursorShape: Qt.PointingHandCursor; onClicked: root.pane = index }
                                }
                            }
                        }
                    }
                    Rectangle {
                        anchors.left: parent.left; anchors.bottom: parent.bottom; anchors.margins: 14
                        width: 30; height: 30; radius: 15; color: xMa.containsMouse ? Theme.hover : Theme.elevated
                        Text { anchors.centerIn: parent; text: root.g(0xF0156); font.family: Theme.fontMono; font.pixelSize: 14; color: Theme.fg }
                        MouseArea { id: xMa; anchors.fill: parent; hoverEnabled: true; cursorShape: Qt.PointingHandCursor; onClicked: Globals.settingsOpen = false }
                    }
                }
                Rectangle { width: 1; height: parent.height; color: Theme.stroke }
                Item {
                    width: parent.width - 211; height: parent.height
                    Text { anchors.left: parent.left; anchors.top: parent.top; anchors.margins: 20; text: root.navItems[root.pane].label; color: Theme.fg; font.family: Theme.fontDisplay; font.pixelSize: Theme.fsTitle; font.weight: Font.Bold }
                    Flickable {
                        anchors.fill: parent; anchors.topMargin: 60; anchors.margins: 20
                        contentHeight: paneLoader.item ? paneLoader.item.implicitHeight : 0
                        clip: true; boundsBehavior: Flickable.StopAtBounds
                        Loader { id: paneLoader; width: parent.width; sourceComponent: [cSystem, cDisplays, cNetwork, cDefaults, cKeyboard, cShortcuts, cTheme, cDock, cUser][root.pane] }
                    }
                }
            }

            // ════════ PANE 0 — System / Diagnostics ════════
            Component {
                id: cSystem
                Column {
                    spacing: 14
                    SectionTitle { text: "AUDIO" }
                    Card {
                        id: audioCard
                        PwObjectTracker { objects: Pipewire.defaultAudioSink ? [Pipewire.defaultAudioSink] : [] }
                        property var sink: Pipewire.defaultAudioSink
                        property bool muted: sink && sink.audio ? sink.audio.muted : false
                        KV { k: "Output"; v: audioCard.sink ? (audioCard.sink.description || audioCard.sink.nickname || audioCard.sink.name) : "—"; dot: audioCard.sink ? (audioCard.muted ? "bad" : "ok") : "bad" }
                        KV { k: "Volume"; v: (audioCard.sink && audioCard.sink.audio ? Math.round(audioCard.sink.audio.volume * 100) : 0) + "%" + (audioCard.muted ? "  ·  muted" : "") }
                        KV { k: "Muted"; action: audioCard.muted; actionLabel: "Unmute"; v: audioCard.muted ? "" : "No"; dot: audioCard.muted ? "bad" : "ok"; onAct: Quickshell.execDetached(["wpctl", "set-mute", "@DEFAULT_AUDIO_SINK@", "0"]) }
                    }
                    SectionTitle { text: "DESKTOP PORTALS  ·  lets apps open links/files & the browser open apps back" }
                    Card {
                        KV { k: "graphical-session.target"; v: root.diag.gsession || "?"; dot: root.diag.gsession === "active" ? "ok" : "bad" }
                        KV { k: "xdg-desktop-portal"; v: root.diag.portal || "?"; dot: root.diag.portal === "active" ? "ok" : "bad" }
                        KV { k: "portal: hyprland"; v: root.diag.portal_hypr || "?"; dot: root.diag.portal_hypr === "active" ? "ok" : "bad" }
                        KV { k: "portal: gtk"; v: root.diag.portal_gtk || "?"; dot: root.diag.portal_gtk === "active" ? "ok" : "bad" }
                        KV { k: "App link handoff (OpenURI)"; v: root.diag.handoff === "ok" ? "working" : "unavailable"; dot: root.diag.handoff === "ok" ? "ok" : "bad" }
                        KV { k: "Default browser"; v: root.appNameForId(root.diag.browser) }
                    }
                    SectionTitle { text: "SYSTEM" }
                    Card {
                        KV { k: "GPU driver"; v: root.diag.gpu || "?"; dot: "info" }
                        KV { k: "VPN"; v: Globals.vpnActive ? "connected" : "off"; dot: Globals.vpnActive ? "ok" : "info" }
                        KV { k: "Idle policy"; v: "lock at 5 min · no display power-off"; dot: "info" }
                        KV { k: "Memory"; v: root.diag.mem || "?"; dot: "info" }
                        KV { k: "Disk /"; v: root.diag.disk || "?"; dot: "info" }
                    }
                    Pill { label: "Re-run checks"; onGo: root.refresh() }
                    Item { width: 1; height: 8 }
                }
            }

            // ════════ PANE 1 — Displays ════════
            Component {
                id: cDisplays
                Column {
                    spacing: 14
                    SectionTitle { text: "ARRANGEMENT  ·  drag a display to reposition it" }
                    Card {
                        visible: root.monitors.length >= 1
                        Item {
                            id: arena
                            width: parent.width; height: 190
                            readonly property real pad: 14
                            readonly property real spanW: { var mx = 1; for (var i = 0; i < root.monitors.length; i++) { var m = root.monitors[i]; mx = Math.max(mx, m.x + m.width / m.scale) } return mx }
                            readonly property real spanH: { var mx = 1; for (var i = 0; i < root.monitors.length; i++) { var m = root.monitors[i]; mx = Math.max(mx, m.y + m.height / m.scale) } return mx }
                            readonly property real factor: Math.min((width - 2 * pad) / spanW, (height - 2 * pad) / spanH)
                            Repeater {
                                model: root.monitors
                                delegate: Rectangle {
                                    id: monBox
                                    required property var modelData
                                    readonly property real lw: modelData.width / modelData.scale
                                    readonly property real lh: modelData.height / modelData.scale
                                    width: lw * arena.factor; height: lh * arena.factor; radius: 8
                                    x: arena.pad + modelData.x * arena.factor
                                    y: arena.pad + modelData.y * arena.factor
                                    color: root.isLaptop(modelData) ? Theme.elevated : Theme.panel
                                    border.color: dragMa.drag.active ? Theme.accent : Theme.stroke; border.width: dragMa.drag.active ? 2 : 1
                                    Column { anchors.centerIn: parent; spacing: 1
                                        Text { anchors.horizontalCenter: parent.horizontalCenter; text: modelData.name; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; font.weight: Font.DemiBold }
                                        Text { anchors.horizontalCenter: parent.horizontalCenter; text: modelData.width + "×" + modelData.height; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: 10 }
                                    }
                                    MouseArea {
                                        id: dragMa; anchors.fill: parent; cursorShape: Qt.SizeAllCursor
                                        drag.target: monBox; drag.axis: Drag.XAndYAxis
                                        drag.minimumX: 0; drag.maximumX: arena.width - monBox.width
                                        drag.minimumY: 0; drag.maximumY: arena.height - monBox.height
                                        onReleased: root.snapArrange(monBox.modelData.name, (monBox.x - arena.pad) / arena.factor, (monBox.y - arena.pad) / arena.factor)
                                    }
                                }
                            }
                        }
                    }
                    SectionTitle { text: "MONITORS" }
                    Repeater {
                        model: root.monitors
                        delegate: Card {
                            id: monCard
                            required property var modelData
                            readonly property var modes: { var seen = {}, out = []; var am = modelData.availableModes || []; for (var i = 0; i < am.length; i++) { var s = String(am[i]).replace("Hz", ""); if (!seen[s]) { seen[s] = 1; out.push(s) } } return out }
                            readonly property string curRes: modelData.width + "x" + modelData.height
                            property bool resOpen: false
                            Item {
                                width: parent.width; height: 20
                                Text { anchors.left: parent.left; anchors.verticalCenter: parent.verticalCenter; text: (monCard.modelData.name || "?") + (root.isLaptop(monCard.modelData) ? "  · built-in" : ""); color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsBody; font.weight: Font.DemiBold }
                                Text { anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; text: (monCard.modelData.description || ""); color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: 10; elide: Text.ElideRight; width: Math.min(implicitWidth, 240) }
                            }
                            KV { k: "Current mode"; v: monCard.modelData.width + "×" + monCard.modelData.height + " @ " + Math.round(monCard.modelData.refreshRate) + "Hz" }
                            KV { k: "Position"; v: monCard.modelData.x + ", " + monCard.modelData.y }
                            Item {
                                width: parent.width; height: 28
                                Text { anchors.left: parent.left; anchors.verticalCenter: parent.verticalCenter; text: "Scale"; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall }
                                Row {
                                    id: scaleRow
                                    anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; spacing: 10
                                    function stepFrom(cur, dir) { var st = [1, 1.25, 1.5, 1.75, 2], best = 0; for (var i = 0; i < st.length; i++) if (Math.abs(st[i] - cur) < Math.abs(st[best] - cur)) best = i; var ni = Math.max(0, Math.min(st.length - 1, best + dir)); return st[ni] }
                                    Rectangle { width: 24; height: 24; radius: 6; color: dMa.containsMouse ? Theme.hover : Theme.panel; border.color: Theme.stroke; border.width: 1
                                        Text { anchors.centerIn: parent; text: "−"; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: 15 }
                                        MouseArea { id: dMa; anchors.fill: parent; hoverEnabled: true; cursorShape: Qt.PointingHandCursor; onClicked: root.applyChange({ name: monCard.modelData.name, scale: scaleRow.stepFrom(monCard.modelData.scale, -1) }) } }
                                    Text { anchors.verticalCenter: parent.verticalCenter; width: 38; horizontalAlignment: Text.AlignHCenter; text: Number(monCard.modelData.scale).toFixed(2) + "×"; color: Theme.accent; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; font.weight: Font.DemiBold }
                                    Rectangle { width: 24; height: 24; radius: 6; color: uMa.containsMouse ? Theme.hover : Theme.panel; border.color: Theme.stroke; border.width: 1
                                        Text { anchors.centerIn: parent; text: "+"; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: 14 }
                                        MouseArea { id: uMa; anchors.fill: parent; hoverEnabled: true; cursorShape: Qt.PointingHandCursor; onClicked: root.applyChange({ name: monCard.modelData.name, scale: scaleRow.stepFrom(monCard.modelData.scale, 1) }) } }
                                }
                            }
                            Item {
                                width: parent.width; height: 28
                                Text { anchors.left: parent.left; anchors.verticalCenter: parent.verticalCenter; text: "Resolution"; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall }
                                Rectangle { anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; width: 160; height: 24; radius: 7; color: rMa.containsMouse ? Theme.hover : Theme.panel; border.color: Theme.stroke; border.width: 1
                                    Text { anchors.left: parent.left; anchors.leftMargin: 8; anchors.verticalCenter: parent.verticalCenter; text: monCard.modelData.width + "×" + monCard.modelData.height; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: 11 }
                                    Text { anchors.right: parent.right; anchors.rightMargin: 8; anchors.verticalCenter: parent.verticalCenter; text: root.g(monCard.resOpen ? 0xF077 : 0xF078); font.family: Theme.fontMono; font.pixelSize: 9; color: Theme.fgDim }
                                    MouseArea { id: rMa; anchors.fill: parent; hoverEnabled: true; cursorShape: Qt.PointingHandCursor; onClicked: monCard.resOpen = !monCard.resOpen } }
                            }
                            Column {
                                width: parent.width; visible: monCard.resOpen; spacing: 1
                                Repeater {
                                    model: monCard.modes
                                    delegate: Rectangle {
                                        required property var modelData
                                        readonly property bool isCur: String(modelData).indexOf(monCard.curRes) === 0
                                        width: parent.width; height: 26; radius: 6; color: mMa.containsMouse ? Theme.hover : "transparent"
                                        Text { anchors.left: parent.left; anchors.leftMargin: 8; anchors.verticalCenter: parent.verticalCenter; text: modelData; color: isCur ? Theme.accent : Theme.fg; font.family: Theme.fontText; font.pixelSize: 11; font.weight: isCur ? Font.DemiBold : Font.Normal }
                                        Text { anchors.right: parent.right; anchors.rightMargin: 8; anchors.verticalCenter: parent.verticalCenter; visible: isCur; text: root.g(0xF012C); font.family: Theme.fontMono; font.pixelSize: 11; color: Theme.accent }
                                        MouseArea { id: mMa; anchors.fill: parent; hoverEnabled: true; cursorShape: Qt.PointingHandCursor; onClicked: { root.applyChange({ name: monCard.modelData.name, mode: String(modelData) }); monCard.resOpen = false } }
                                    }
                                }
                            }
                        }
                    }
                    Text { width: parent.width; text: "Changes apply live and persist to generated/user.lua."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: 11; wrapMode: Text.Wrap }
                    Item { width: 1; height: 8 }
                }
            }

            // ════════ PANE 2 — Networking ════════
            Component {
                id: cNetwork
                Column {
                    spacing: 14
                    // Wired / Ethernet
                    SectionTitle { text: "WIRED" }
                    Card {
                        Text { width: parent.width; visible: root.wiredList.length === 0; text: "No wired connection."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall }
                        Repeater {
                            model: root.wiredList
                            delegate: Item {
                                required property var modelData
                                width: parent.width; height: 30
                                Text { anchors.left: parent.left; anchors.leftMargin: 4; anchors.verticalCenter: parent.verticalCenter; text: root.g(0xF0200); font.family: Theme.fontMono; font.pixelSize: 13; color: modelData.state === "activated" ? Theme.accent : Theme.fgDim }
                                Text { anchors.left: parent.left; anchors.leftMargin: 28; anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; text: modelData.name + "  ·  " + modelData.dev + (modelData.state === "activated" ? "  ·  connected" : ""); color: modelData.state === "activated" ? Theme.accent : Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; font.weight: modelData.state === "activated" ? Font.DemiBold : Font.Normal; elide: Text.ElideRight }
                            }
                        }
                    }
                    // Wi-Fi
                    Item {
                        width: parent.width; height: 30
                        SectionTitle { anchors.left: parent.left; anchors.verticalCenter: parent.verticalCenter; text: "WI-FI" }
                        Toggle { visible: root.hasWifi; anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; on: root.wifiOn; onToggled: { Quickshell.execDetached(["nmcli", "radio", "wifi", root.wifiOn ? "off" : "on"]); wifiRescan.restart() } }
                        Text { visible: !root.hasWifi; anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; text: "Not available"; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall }
                    }
                    Card {
                        visible: !root.hasWifi
                        Text { width: parent.width; text: root.g(0xF092F) + "  No Wi-Fi adapter detected — this machine has no wireless device (common in VMs). Use the wired connection above, or plug in a USB Wi-Fi dongle."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; wrapMode: Text.Wrap }
                    }
                    Card {
                        visible: root.hasWifi && root.wifiOn
                        Repeater {
                            model: root.wifiList.slice(0, 8)
                            delegate: Column {
                                required property var modelData
                                width: parent.width
                                Item {
                                    width: parent.width; height: 30
                                    Rectangle { anchors.fill: parent; radius: 7; color: wMa.containsMouse ? Theme.hover : "transparent" }
                                    Text { anchors.left: parent.left; anchors.leftMargin: 4; anchors.verticalCenter: parent.verticalCenter; text: modelData.signal >= 66 ? root.g(0xF0925) : (modelData.signal >= 33 ? root.g(0xF0922) : root.g(0xF091F)); font.family: Theme.fontMono; font.pixelSize: 13; color: modelData.active ? Theme.accent : Theme.fgDim }
                                    Text { anchors.left: parent.left; anchors.leftMargin: 28; anchors.right: parent.right; anchors.rightMargin: 22; anchors.verticalCenter: parent.verticalCenter; text: modelData.ssid; color: modelData.active ? Theme.accent : Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; font.weight: modelData.active ? Font.DemiBold : Font.Normal; elide: Text.ElideRight }
                                    Text { anchors.right: parent.right; anchors.rightMargin: 4; anchors.verticalCenter: parent.verticalCenter; visible: modelData.sec !== ""; text: root.g(0xF033E); font.family: Theme.fontMono; font.pixelSize: 10; color: Theme.fgDim }
                                    MouseArea { id: wMa; anchors.fill: parent; hoverEnabled: true; cursorShape: Qt.PointingHandCursor; onClicked: root.connectWifi(modelData.ssid, modelData.sec) }
                                }
                                Item {
                                    width: parent.width; height: visible ? 34 : 0; visible: root.pwTarget === modelData.ssid
                                    Rectangle { anchors.fill: parent; anchors.topMargin: 2; anchors.bottomMargin: 4; radius: 7; color: Theme.panel; border.color: Theme.accent; border.width: 1
                                        TextInput { id: pwIn; anchors.fill: parent; anchors.leftMargin: 10; anchors.rightMargin: 52; verticalAlignment: TextInput.AlignVCenter; echoMode: TextInput.Password; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall
                                            onTextChanged: root.pwText = text; Component.onCompleted: forceActiveFocus(); onAccepted: root.connectWifi(modelData.ssid, modelData.sec)
                                            Text { anchors.verticalCenter: parent.verticalCenter; visible: pwIn.text.length === 0; text: "Password"; color: Theme.fgDim; font: pwIn.font } }
                                        Text { anchors.right: parent.right; anchors.rightMargin: 12; anchors.verticalCenter: parent.verticalCenter; text: "Join"; color: Theme.accent; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; font.weight: Font.DemiBold; MouseArea { anchors.fill: parent; anchors.margins: -6; cursorShape: Qt.PointingHandCursor; onClicked: root.connectWifi(modelData.ssid, modelData.sec) } } }
                                }
                            }
                        }
                    }
                    // VPN
                    Item {
                        width: parent.width; height: 20
                        SectionTitle { anchors.left: parent.left; anchors.verticalCenter: parent.verticalCenter; text: "VPN" }
                        Text { anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; text: "+ Add VPN"; color: Theme.accent; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; font.weight: Font.DemiBold; MouseArea { anchors.fill: parent; anchors.margins: -6; cursorShape: Qt.PointingHandCursor; onClicked: Quickshell.execDetached(["nm-connection-editor"]) } }
                    }
                    Card {
                        Text { width: parent.width; visible: root.vpnList.length === 0; text: "No VPN connections configured."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall }
                        Repeater {
                            model: root.vpnList
                            delegate: Item {
                                required property var modelData
                                width: parent.width; height: 30
                                Rectangle { anchors.fill: parent; radius: 7; color: vMa.containsMouse ? Theme.hover : "transparent" }
                                Text { anchors.left: parent.left; anchors.leftMargin: 4; anchors.verticalCenter: parent.verticalCenter; text: root.g(0xF0582); font.family: Theme.fontMono; font.pixelSize: 12; color: modelData.active ? Theme.accent : Theme.fgDim }
                                Text { anchors.left: parent.left; anchors.leftMargin: 26; anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; text: modelData.name + (modelData.active ? "  ·  connected" : ""); color: modelData.active ? Theme.accent : Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; font.weight: modelData.active ? Font.DemiBold : Font.Normal; elide: Text.ElideRight }
                                MouseArea { id: vMa; anchors.fill: parent; hoverEnabled: true; cursorShape: Qt.PointingHandCursor; onClicked: { Quickshell.execDetached(["nmcli", "connection", modelData.active ? "down" : "up", modelData.name]); vpnRescan.restart() } }
                            }
                        }
                    }
                    // SSH
                    Item {
                        width: parent.width; height: 20
                        SectionTitle { anchors.left: parent.left; anchors.verticalCenter: parent.verticalCenter; text: "SSH HOSTS" }
                        Text { anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; text: "Edit config"; color: Theme.accent; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; font.weight: Font.DemiBold; MouseArea { anchors.fill: parent; anchors.margins: -6; cursorShape: Qt.PointingHandCursor; onClicked: Quickshell.execDetached(["foot", "-e", "sh", "-c", "${EDITOR:-nvim} ~/.ssh/config"]) } }
                    }
                    Card {
                        Text { width: parent.width; visible: root.sshHosts.length === 0; text: "No hosts in ~/.ssh/config. Add one with “Edit config”."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; wrapMode: Text.Wrap }
                        Repeater {
                            model: root.sshHosts
                            delegate: Item {
                                required property var modelData
                                width: parent.width; height: 30
                                Rectangle { anchors.fill: parent; radius: 7; color: sMa.containsMouse ? Theme.hover : "transparent" }
                                Text { anchors.left: parent.left; anchors.leftMargin: 4; anchors.verticalCenter: parent.verticalCenter; text: root.g(0xF08C0); font.family: Theme.fontMono; font.pixelSize: 12; color: Theme.fgDim }
                                Text { anchors.left: parent.left; anchors.leftMargin: 26; anchors.verticalCenter: parent.verticalCenter; text: modelData; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall }
                                Text { anchors.right: parent.right; anchors.rightMargin: 6; anchors.verticalCenter: parent.verticalCenter; visible: sMa.containsMouse; text: "connect →"; color: Theme.accent; font.family: Theme.fontText; font.pixelSize: 11 }
                                MouseArea { id: sMa; anchors.fill: parent; hoverEnabled: true; cursorShape: Qt.PointingHandCursor; onClicked: Quickshell.execDetached(["foot", "-e", "ssh", modelData]) }
                            }
                        }
                    }
                    // Status
                    SectionTitle { text: "STATUS" }
                    Card {
                        Repeater {
                            model: root.netActive
                            delegate: KV { required property var modelData; k: modelData.name + " (" + modelData.type + ")"; v: modelData.dev + " · " + modelData.state; dot: modelData.state === "activated" ? "ok" : "info" }
                        }
                        Repeater { model: root.ipList; delegate: KV { required property var modelData; k: "IP"; v: modelData } }
                    }
                    Item { width: 1; height: 8 }
                }
            }

            // ════════ PANE 3 — Default Apps ════════
            Component {
                id: cDefaults
                Column {
                    id: defCol
                    spacing: 10
                    property string openCat: ""
                    Repeater {
                        model: root.appCats
                        delegate: Card {
                            id: appCard
                            required property var modelData
                            readonly property string curId: root.defaults[modelData.key] || ""
                            readonly property var choices: root.appChoices[modelData.key] || []
                            Item {
                                width: parent.width; height: 30
                                Row {
                                    anchors.left: parent.left; anchors.verticalCenter: parent.verticalCenter; spacing: 10
                                    Text { anchors.verticalCenter: parent.verticalCenter; width: 18; text: root.g(appCard.modelData.ic); font.family: Theme.fontMono; font.pixelSize: 15; color: Theme.fgDim }
                                    Text { anchors.verticalCenter: parent.verticalCenter; text: appCard.modelData.key; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; font.weight: Font.DemiBold }
                                }
                                Rectangle {
                                    anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter
                                    width: 210; height: 26; radius: 7; color: cMa.containsMouse ? Theme.hover : Theme.panel; border.color: Theme.stroke; border.width: 1
                                    Text { anchors.left: parent.left; anchors.leftMargin: 9; anchors.right: chev.left; anchors.verticalCenter: parent.verticalCenter; text: root.appNameForId(appCard.curId); color: Theme.fg; font.family: Theme.fontText; font.pixelSize: 11; elide: Text.ElideRight }
                                    Text { id: chev; anchors.right: parent.right; anchors.rightMargin: 8; anchors.verticalCenter: parent.verticalCenter; text: root.g(0xF078); font.family: Theme.fontMono; font.pixelSize: 9; color: Theme.fgDim }
                                    MouseArea { id: cMa; anchors.fill: parent; hoverEnabled: true; cursorShape: Qt.PointingHandCursor; onClicked: defCol.openCat = (defCol.openCat === appCard.modelData.key ? "" : appCard.modelData.key) }
                                }
                            }
                            Column {
                                width: parent.width; visible: defCol.openCat === appCard.modelData.key; spacing: 1
                                Text { width: parent.width; visible: appCard.choices.length === 0; text: "No installed app handles this type."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: 11 }
                                Repeater {
                                    model: appCard.choices
                                    delegate: Rectangle {
                                        required property var modelData
                                        readonly property var entry: root.entryForId(modelData)
                                        readonly property bool isCur: String(appCard.curId).replace(/\.desktop$/, "") === String(modelData).replace(/\.desktop$/, "")
                                        width: parent.width; height: 32; radius: 6; color: eMa.containsMouse ? Theme.hover : "transparent"
                                        Row {
                                            anchors.left: parent.left; anchors.leftMargin: 8; anchors.verticalCenter: parent.verticalCenter; spacing: 9
                                            Image { anchors.verticalCenter: parent.verticalCenter; width: 18; height: 18; sourceSize.width: 36; sourceSize.height: 36; source: parent.parent.entry && parent.parent.entry.icon ? Quickshell.iconPath(parent.parent.entry.icon, "application-x-executable") : Quickshell.iconPath("application-x-executable") }
                                            Text { anchors.verticalCenter: parent.verticalCenter; text: parent.parent.entry ? (parent.parent.entry.name || modelData) : modelData; color: parent.parent.isCur ? Theme.accent : Theme.fg; font.family: Theme.fontText; font.pixelSize: 11; font.weight: parent.parent.isCur ? Font.DemiBold : Font.Normal }
                                        }
                                        Text { anchors.right: parent.right; anchors.rightMargin: 8; anchors.verticalCenter: parent.verticalCenter; visible: parent.isCur; text: root.g(0xF012C); font.family: Theme.fontMono; font.pixelSize: 11; color: Theme.accent }
                                        MouseArea { id: eMa; anchors.fill: parent; hoverEnabled: true; cursorShape: Qt.PointingHandCursor; onClicked: { root.setDefaultApp(appCard.modelData.key, modelData); defCol.openCat = "" } }
                                    }
                                }
                            }
                        }
                    }
                    Item { width: 1; height: 8 }
                }
            }

            // ════════ PANE 4 — Keyboard ════════
            Component {
                id: cKeyboard
                Column {
                    id: kbPane
                    spacing: 14
                    property var active: root.kbLayout.split(",").filter(function (x) { return x.trim() !== "" })
                    property string kbQuery: ""
                    function nameOf(code) { for (var i = 0; i < root.kbPresets.length; i++) if (root.kbPresets[i].c === code) return root.kbPresets[i].n; return code }
                    // layouts not already active, matching the search query (name or code)
                    function filtered() {
                        var q = kbPane.kbQuery.trim().toLowerCase()
                        var act = root.kbLayout.split(",")
                        var out = []
                        for (var i = 0; i < root.kbPresets.length; i++) {
                            var p = root.kbPresets[i]
                            if (act.indexOf(p.c) >= 0) continue
                            if (q === "" || p.n.toLowerCase().indexOf(q) >= 0 || p.c.toLowerCase().indexOf(q) >= 0) out.push(p)
                        }
                        return out
                    }
                    function addLayout(code) {
                        var a = root.kbLayout.split(",").filter(function (x) { return x.trim() !== "" })
                        if (a.indexOf(code) < 0) a.push(code)
                        root.applyKb(a.join(","))
                    }
                    SectionTitle { text: "ACTIVE LAYOUTS  ·  switch with Super+Shift+Space" }
                    Card {
                        Flow {
                            width: parent.width; spacing: 8
                            Repeater {
                                model: kbPane.active
                                delegate: Rectangle {
                                    required property var modelData
                                    required property int index
                                    height: 30; width: chipRow.implicitWidth + 18; radius: 8; color: Theme.accent
                                    Row { id: chipRow; anchors.centerIn: parent; spacing: 7
                                        Text { anchors.verticalCenter: parent.verticalCenter; text: kbPane.nameOf(modelData) + " (" + modelData + ")"; color: Theme.accentText; font.family: Theme.fontText; font.pixelSize: 11; font.weight: Font.DemiBold }
                                        Text { anchors.verticalCenter: parent.verticalCenter; visible: kbPane.active.length > 1; text: root.g(0xF0156); font.family: Theme.fontMono; font.pixelSize: 11; color: Theme.accentText
                                            MouseArea { anchors.fill: parent; anchors.margins: -5; cursorShape: Qt.PointingHandCursor; onClicked: { var a = root.kbLayout.split(",").filter(function (x) { return x.trim() !== "" }); a.splice(index, 1); if (a.length) root.applyKb(a.join(",")) } } }
                                    }
                                }
                            }
                        }
                    }
                    SectionTitle { text: "ADD A LAYOUT  ·  " + root.kbPresets.length + " languages" }
                    Card {
                        Column {
                            width: parent.width; spacing: 10
                            // search field
                            Rectangle {
                                width: parent.width; height: 34; radius: Theme.radiusInner
                                color: Theme.bg; border.color: kbSearch.activeFocus ? Theme.accent : Theme.stroke; border.width: 1
                                Text { anchors.left: parent.left; anchors.leftMargin: 11; anchors.verticalCenter: parent.verticalCenter; text: root.g(0xF0349); font.family: Theme.fontMono; font.pixelSize: 13; color: Theme.fgDim }
                                TextInput {
                                    id: kbSearch
                                    anchors.fill: parent; anchors.leftMargin: 34; anchors.rightMargin: 12; verticalAlignment: TextInput.AlignVCenter; clip: true
                                    color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall
                                    onTextChanged: kbPane.kbQuery = text
                                    // Enter adds the first match
                                    onAccepted: { var f = kbPane.filtered(); if (f.length) { kbPane.addLayout(f[0].c); text = "" } }
                                    Text { anchors.verticalCenter: parent.verticalCenter; visible: kbSearch.text.length === 0; text: "Search languages… (e.g. German, fr, العربية)"; color: Theme.fgDim; font: kbSearch.font }
                                }
                            }
                            // matching layouts (chips) — click to add
                            Flow {
                                width: parent.width; spacing: 8
                                Repeater {
                                    model: kbPane.filtered()
                                    delegate: Rectangle {
                                        required property var modelData
                                        height: 28; width: addRow.implicitWidth + 18; radius: 8; color: aMa3.containsMouse ? Theme.accent : Theme.panel; border.color: Theme.stroke; border.width: 1
                                        Row { id: addRow; anchors.centerIn: parent; spacing: 6
                                            Text { anchors.verticalCenter: parent.verticalCenter; text: "+"; color: aMa3.containsMouse ? Theme.accentText : Theme.accent; font.family: Theme.fontText; font.pixelSize: 13 }
                                            Text { anchors.verticalCenter: parent.verticalCenter; text: modelData.n + "  (" + modelData.c + ")"; color: aMa3.containsMouse ? Theme.accentText : Theme.fg; font.family: Theme.fontText; font.pixelSize: 11 }
                                        }
                                        MouseArea { id: aMa3; anchors.fill: parent; hoverEnabled: true; cursorShape: Qt.PointingHandCursor; onClicked: kbPane.addLayout(modelData.c) }
                                    }
                                }
                            }
                            Text { width: parent.width; visible: kbPane.filtered().length === 0; text: "No matching layout."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall }
                        }
                    }
                    Text { width: parent.width; text: "Switch with Super+Shift+Space. Per-window layout memory is handled by the kb-per-window daemon."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: 11; wrapMode: Text.Wrap }
                    Item { width: 1; height: 8 }
                }
            }

            // ════════ PANE 5 — Shortcuts ════════
            Component {
                id: cShortcuts
                Column {
                    spacing: 6
                    Repeater {
                        model: root.shortcutsModel()
                        delegate: Item {
                            required property var modelData
                            width: parent.width
                            height: modelData.h ? 30 : 24
                            SectionTitle { visible: modelData.h; anchors.left: parent.left; anchors.bottom: parent.bottom; text: modelData.a; font.pixelSize: Theme.fsBody; color: Theme.fg }
                            Text { visible: !modelData.h; anchors.left: parent.left; anchors.verticalCenter: parent.verticalCenter; width: 180; text: modelData.a; color: Theme.accent; font.family: Theme.fontMono; font.pixelSize: 11 }
                            Text { visible: !modelData.h; anchors.left: parent.left; anchors.leftMargin: 190; anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; text: modelData.b; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; elide: Text.ElideRight }
                        }
                    }
                    Item { width: 1; height: 8 }
                }
            }

            // ════════ PANE 6 — Theme & Accent ════════
            Component {
                id: cTheme
                Column {
                    spacing: 14
                    SectionTitle { text: "APP APPEARANCE" }
                    Card {
                        Row {
                            width: parent.width; spacing: 8
                            Repeater {
                                model: [{ n: "Light", m: "light", ic: 0xF0599 }, { n: "Dark", m: "dark", ic: 0xF0594 }]
                                delegate: Rectangle {
                                    required property var modelData
                                    readonly property bool sel: Globals.colorScheme === modelData.m
                                    width: (parent.width - 8) / 2; height: 38; radius: Theme.radiusInner
                                    color: sel ? Theme.accent : Theme.panel
                                    border.color: sel ? Theme.accent : Theme.stroke; border.width: 1
                                    Row {
                                        anchors.centerIn: parent; spacing: 7
                                        Text { anchors.verticalCenter: parent.verticalCenter; text: root.g(modelData.ic); font.family: Theme.fontMono; font.pixelSize: 15; color: parent.parent.sel ? Theme.accentText : Theme.fg }
                                        Text { anchors.verticalCenter: parent.verticalCenter; text: modelData.n; color: parent.parent.sel ? Theme.accentText : Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; font.weight: Font.DemiBold }
                                    }
                                    MouseArea { anchors.fill: parent; cursorShape: Qt.PointingHandCursor; onClicked: root.setColorScheme(modelData.m) }
                                }
                            }
                        }
                    }
                    Text { width: parent.width; text: "Light/dark applies to GTK + Qt apps (Nautilus, editors, settings dialogs). The shell stays dark. Open apps may need a relaunch to fully recolour."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: 11; wrapMode: Text.Wrap }
                    SectionTitle { text: "ACCENT COLOUR" }
                    Card {
                        Flow {
                            width: parent.width; spacing: 10
                            Repeater {
                                model: root.accents
                                delegate: Rectangle {
                                    required property var modelData
                                    width: 46; height: 46; radius: 23; color: modelData.hex
                                    readonly property bool sel: root.hex6(Globals.accentColor).toLowerCase() === root.hex6(modelData.hex).toLowerCase()
                                    border.color: sel ? Theme.fg : Qt.rgba(1, 1, 1, 0.15); border.width: sel ? 3 : 1
                                    Text { anchors.centerIn: parent; visible: parent.sel; text: root.g(0xF012C); font.family: Theme.fontMono; font.pixelSize: 18; color: "white" }
                                    MouseArea { anchors.fill: parent; cursorShape: Qt.PointingHandCursor; onClicked: root.setAccent(modelData.hex) }
                                }
                            }
                        }
                        Item {
                            width: parent.width; height: 30
                            Text { anchors.left: parent.left; anchors.verticalCenter: parent.verticalCenter; text: "Custom hex"; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall }
                            Rectangle { anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; width: 130; height: 26; radius: 7; color: Theme.panel; border.color: hexIn.activeFocus ? Theme.accent : Theme.stroke; border.width: 1
                                TextInput { id: hexIn; anchors.fill: parent; anchors.leftMargin: 9; anchors.rightMargin: 9; verticalAlignment: TextInput.AlignVCenter; color: Theme.fg; font.family: Theme.fontMono; font.pixelSize: 12; text: String(Globals.accentColor)
                                    onAccepted: { var t = text.trim(); if (/^#?[0-9a-fA-F]{6}$/.test(t)) root.setAccent(t[0] === "#" ? t : "#" + t) } } }
                        }
                    }
                    SectionTitle { text: "WINDOW BORDERS" }
                    Card {
                        Item {
                            width: parent.width; height: 30
                            Column { anchors.left: parent.left; anchors.verticalCenter: parent.verticalCenter; spacing: 1
                                Text { text: "Tint window borders with accent"; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall }
                                Text { text: "Replaces the default border colour with your accent."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: 10 }
                            }
                            Toggle { anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; on: Globals.tintBorders; onToggled: { Globals.tintBorders = !Globals.tintBorders; root.applyBorder(); root.setAccent(String(Globals.accentColor)) } }
                        }
                    }
                    SectionTitle { text: "ANIMATIONS" }
                    Card {
                        Row {
                            width: parent.width; spacing: 8
                            Repeater {
                                model: [{ n: "Off", m: 0 }, { n: "Smooth", m: 0.7 }, { n: "Normal", m: 1 }, { n: "Fast", m: 1.6 }]
                                delegate: Rectangle {
                                    required property var modelData
                                    readonly property bool sel: Math.abs(Globals.animationSpeed - modelData.m) < 0.001
                                    width: (parent.width - 24) / 4; height: 32; radius: Theme.radiusInner
                                    color: sel ? Theme.accent : Theme.panel
                                    border.color: sel ? Theme.accent : Theme.stroke; border.width: 1
                                    Text { anchors.centerIn: parent; text: modelData.n; color: parent.sel ? Theme.accentText : Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall; font.weight: Font.DemiBold }
                                    MouseArea { anchors.fill: parent; cursorShape: Qt.PointingHandCursor; onClicked: root.setAnim(modelData.m) }
                                }
                            }
                        }
                    }
                    Text { width: parent.width; text: "Animation speed drives window + shell motion; applies live and persists to user-theme.json + generated/user.lua."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: 11; wrapMode: Text.Wrap }
                    Text { width: parent.width; text: "Accent recolours the whole shell instantly and persists in user-theme.json."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: 11; wrapMode: Text.Wrap }
                    Item { width: 1; height: 8 }
                }
            }

            // ════════ PANE — Dock ════════
            Component {
                id: cDock
                Column {
                    spacing: 14
                    SectionTitle { text: "BOTTOM DOCK" }
                    Card {
                        Item {
                            width: parent.width; height: 30
                            Column { anchors.left: parent.left; anchors.verticalCenter: parent.verticalCenter; spacing: 1
                                Text { text: "Show dock"; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall }
                                Text { text: "Launcher · overview · workspace switcher at the bottom."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: 10 }
                            }
                            Toggle { anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; on: Globals.dockEnabled; onToggled: { Globals.dockEnabled = !Globals.dockEnabled; root.writePrefs() } }
                        }
                        Rectangle { width: parent.width; height: 1; color: Theme.stroke; opacity: 0.5 }
                        Item {
                            width: parent.width; height: 30
                            opacity: Globals.dockEnabled ? 1 : 0.4
                            Column { anchors.left: parent.left; anchors.verticalCenter: parent.verticalCenter; spacing: 1
                                Text { text: "Intelligent hide"; color: Theme.fg; font.family: Theme.fontText; font.pixelSize: Theme.fsSmall }
                                Text { text: "Auto-hide; reveal by moving the cursor to the bottom edge."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: 10 }
                            }
                            Toggle { anchors.right: parent.right; anchors.verticalCenter: parent.verticalCenter; on: Globals.dockAutohide; onToggled: { if (Globals.dockEnabled) { Globals.dockAutohide = !Globals.dockAutohide; root.writePrefs() } } }
                        }
                    }
                    Text { width: parent.width; text: "The dock replaces the workspace row that used to be in the top bar."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: 11; wrapMode: Text.Wrap }
                    Item { width: 1; height: 8 }
                }
            }

            // ════════ PANE — User ════════
            Component {
                id: cUser
                Column {
                    spacing: 14
                    SectionTitle { text: "ACCOUNT" }
                    Card {
                        Row {
                            width: parent.width; spacing: 16
                            Rectangle {
                                width: 72; height: 72; radius: 36; color: Theme.elevated; border.color: Theme.stroke; border.width: 1; clip: true
                                Image { id: avatarImg; anchors.fill: parent; fillMode: Image.PreserveAspectCrop; cache: false; source: root.hasFace ? ("file://" + root.home + "/.face?v=" + root.avatarTick) : ""; visible: root.hasFace && status === Image.Ready }
                                Text { anchors.centerIn: parent; visible: !avatarImg.visible; text: root.g(0xF0004); font.family: Theme.fontMono; font.pixelSize: 34; color: Theme.fgDim }
                            }
                            Column {
                                anchors.verticalCenter: parent.verticalCenter; spacing: 6
                                Text { text: Quickshell.env("USER") || "user"; color: Theme.fg; font.family: Theme.fontDisplay; font.pixelSize: Theme.fsLarge; font.weight: Font.Bold }
                                Pill { label: "Change avatar…"; onGo: avatarDlg.open() }
                            }
                        }
                    }
                    Text { width: parent.width; text: "Avatar is saved to ~/.face (used by login/greeters); we also try to update the system account icon."; color: Theme.fgDim; font.family: Theme.fontText; font.pixelSize: 11; wrapMode: Text.Wrap }
                    Item { width: 1; height: 8 }
                }
            }
        }
    }
}
